[workspace]
members = [
    "id_1",
    "id_2",
    "id_3",
    "id_4",
    "id_5",
    "id_6",
    "id_7"
]
resolver = "2"

[workspace.dependencies]

[profile.release]
lto = "fat"
codegen-units = 1

[build]
rustflags = ["-C", "target-cpu=native"]